import 'package:voice_changer_flutter/data/model/effect.dart';

List<Effect> listEffects() {
  return [
    Effect(name: "No Effect", pitch: 0, speed: 1),
    Effect(name: "Robot", pitch: -500,
      speed: 1.2,
      amplify: 5.0,
      newEcho: [0.2, 0.5, 0.7],
      newReverb: ReverbType.largeHall2,
      filter: FilterType.bandPass,
      eq1: [200.0, 1.5, 3.0],
      eq2: [500.0, 1.0, -2.0],
      eq3: [1000.0, 2.0, 5.0],
      distort: [0.8, 0.5, 0.3],
      distortType: DistortType.speechRadioTower,),
    Effect(name: "Cave", pitch: -300, speed: 0.9, amplify: 3.0, newEcho: [0.3, 0.6, 0.5], newReverb: ReverbType.cathedral, filter: FilterType.bandPass, eq1: [150.0, 1.2, 2.5], eq2: [400.0, 1.5, 1.0], eq3: [1200.0, 2.0, -2.0], distort: [0.2, 0.3, 0.4], distortType: DistortType.speechCosmicInterference,),
    Effect(name: "Monster", pitch: -400, speed: 0.85, amplify: 2.0, newReverb: ReverbType.mediumRoom, filter: FilterType.lowPass, eq1: [100, 10, 10], distortType: DistortType.multiDecimated4,),
    Effect(name: "Nervous", pitch: 1, speed: 1.3, newEcho: [0.05, 0.05, 0.2], filter: FilterType.highPass, eq1: [2000, 10, 5],),
    Effect(name: "Drunk", pitch: -200, speed: 0.81, newEcho: [0.15, 0.1, 0.3], newReverb: ReverbType.mediumRoom, distortType: DistortType.multiDecimated2),
    Effect(name: "Squirrel", pitch: 480, speed: 1.06),
    Effect(name: "Girl", pitch: 400, speed: 1.01),
    Effect(name: "Child", pitch: 240, speed: 1),
    Effect(name: "Death", pitch: -600, speed: 0.7, amplify: 5.0, newEcho: [0.2, 0.5, 0.8], newReverb: ReverbType.largeHall2, filter: FilterType.lowPass, eq1: [200.0, 1.0, 3.0], eq2: [800.0, 1.0, -2.0], eq3: [3000.0, 1.0, -5.0], distort: [0.3, 0.6, 0.9], distortType: DistortType.multiDecimated4),
    Effect(name: "Grand Canyon", pitch: 0, speed: 0.77, newEcho: [0.4, 0.4, 0.7], newReverb: ReverbType.largeRoom2),
    Effect(name: "Man", pitch: -400, speed: 1.01),
    Effect(name: "Telephone", pitch: 0, speed: 1.0, amplify: 0.0, newEcho: [0.05, 0.3, 0.5], newReverb: ReverbType.mediumRoom, filter: FilterType.bandPass, eq1: [300.0, 1.0, -5.0], eq2: [1000.0, 1.0, 2.0], eq3: [4000.0, 1.0, -8.0], distort: [0.2, 0.4, 0.6], distortType: DistortType.speechRadioTower,),
    Effect(name: "Underwater", pitch: -500, speed: 0.6, amplify: 4.0, newEcho: [0.3, 0.4, 0.7], newReverb: ReverbType.mediumChamber, filter: FilterType.lowPass, eq1: [150.0, 1.0, 5.0], eq2: [600.0, 1.0, -3.0], eq3: [2500.0, 1.0, -6.0], distort: [0.2, 0.5, 0.8], distortType: DistortType.multiDecimated4),
    Effect(name: "Extraterrestrial", pitch: 120, speed: 0.79),
    Effect(name: "Factory", pitch: 0, speed: 1, amplify: 2, newEcho: [0.2, 0.3, 0.5]),
    Effect(name: "Villain", pitch: -200, speed: 0.85, amplify: 3, filter: FilterType.highPass),
    Effect(name: "Zombie", pitch: -600,
      speed: 0.7,
      amplify: 3.5,
      newEcho: [0.2, 0.3, 0.6],
      newReverb: ReverbType.largeRoom2,
      filter: FilterType.bandPass,
      eq1: [200.0, 1.2, 4.0],
      eq2: [800.0, 1.0, -2.0],
      eq3: [3000.0, 1.5, -5.0],
      distort: [0.3, 0.6, 0.9],
      distortType: DistortType.multiEverythingIsBroken,),
    Effect(name: "Megaphone", pitch: 200, speed: 1, amplify: 4, eq1: [125, 18, -10], eq2: [400, 18, 15], eq3: [400, 18, -10], distort: [0.2, 0.4, 0.8], distortType: DistortType.speechRadioTower),
    Effect(name: "Alien", pitch: 160, speed: 0.9, newEcho: [0.18, 0.75, 0.75]),
    Effect(name: "Small Alien", pitch: 320, speed: 1.03, newEcho: [0.18, 0.76, 0.75]),
    Effect(name: "StormWind", pitch: 40, speed: 1.3, amplify: 5, newEcho: [0.2, 0.75, 1]),
    Effect(name: "Motorcycle", pitch: -40, speed: 1, newEcho: [0.1, 0.1, 0.3]),
    Effect(name: "Parody", pitch: 0, speed: 1, newEcho: [0.2, 0.75, 1]),
    Effect(name: "Basso Singer", pitch: -160, speed: 1, eq1: [125, 18, 15], eq2: [400, 18, -10], eq3: [4000, 18, -10], newReverb: ReverbType.cathedral),
    Effect(name: "Mr Panic", pitch: 120, speed: 1.18, eq1: [125, 18, -10], eq2: [400, 18, 15], eq3: [4000, 18, -10], newReverb: ReverbType.mediumHall2),
    Effect(name: "Ghost", pitch: -300, speed: 0.9, newEcho: [0.3, 0.6, 0.7], newReverb: ReverbType.largeHall2, filter: FilterType.lowPass, distort: [0.1, 0.3, 0.5], distortType: DistortType.multiDistortedFunk),
    Effect(name: "Baby Girl", pitch: 1.0, speed: 1.0, newReverb: ReverbType.largeRoom, distortType: DistortType.drumsBitBrush, filter: FilterType.bandPass),
    Effect(name: "Boy", pitch: 300, speed: 1.1, newEcho: [1.0, 1.0, 1.0], newReverb: ReverbType.smallRoom, distortType: DistortType.drumsBitBrush, filter: FilterType.bandPass),
    Effect(name: "Bunny girl", pitch: 1.40, speed: 1.32, newEcho: [1.0, 1.0, 1.0], newReverb: ReverbType.smallRoom, distortType: DistortType.multiDistortedCubed, filter: FilterType.bandPass),
    Effect(name: "Cassette Tape", pitch: 1.40, speed: 1.32, newEcho: [0.43, 0.68, 0.78], newReverb: ReverbType.mediumRoom, distortType: DistortType.multiCellphoneConcert, filter: FilterType.bandPass),
    Effect(name: "Monster 2", pitch: 1.46, speed: 1.03, newEcho: [0.46, 0.54, 0.54], newReverb: ReverbType.mediumRoom, distortType: DistortType.drumsLoFi, filter: FilterType.bandPass),
    Effect(name: "Maiden", pitch: 1.46, speed: 1.03, newEcho: [0.46, 0.54, 0.54], newReverb: ReverbType.mediumRoom, distortType: DistortType.drumsLoFi, filter: FilterType.bandPass),
    Effect(name: "Love Robot", pitch: 1.66, speed: 0.70, newEcho: [0.23, 0.37, 0.17], newReverb: ReverbType.mediumChamber, distortType: DistortType.drumsLoFi, filter: FilterType.bandPass),
    Effect(name: "Loudspeaker", pitch: 1.66, speed: 0.70, newEcho: [0.23, 0.37, 0.17], newReverb: ReverbType.cathedral, distortType: DistortType.drumsLoFi, filter: FilterType.bandPass),
    Effect(name: "Joker", pitch: 1.66, speed: 0.70, newEcho: [0.23, 0.37, 0.17], newReverb: ReverbType.largeHall2, distortType: DistortType.drumsLoFi, filter: FilterType.bandPass),
    Effect(name: "Baby Boy", pitch: 1.66, speed: 1.01, newEcho: [0.82, 0.82, 0.75], newReverb: ReverbType.largeHall2, distortType: DistortType.speechRadioTower, filter: FilterType.bandPass),
    Effect(name: "Horror", pitch: 1.66, speed: 1.01, newEcho: [0.82, 0.82, 0.75], newReverb: ReverbType.largeHall2, distortType: DistortType.speechRadioTower, filter: FilterType.bandPass),
    Effect(name: "Cute Ghost", pitch: 1.66, speed: 1.01, newEcho: [0.82, 0.82, 0.75], newReverb: ReverbType.largeHall2, distortType: DistortType.speechRadioTower, filter: FilterType.bandPass),
    Effect(name: "Freak", pitch: 1.66, speed: 1.77, newEcho: [0.82, 0.82, 0.75], newReverb: ReverbType.smallRoom, distortType: DistortType.drumsBitBrush, filter: FilterType.bandPass),
    Effect(name: "Fighting Robot", pitch: 1.66, speed: 1.77, newEcho: [0.82, 0.82, 0.75], newReverb: ReverbType.smallRoom, distortType: DistortType.drumsLoFi, filter: FilterType.bandPass),
    Effect(name: "Elf", pitch: 1.66, speed: 1.77, newEcho: [0.82, 0.82, 0.75], newReverb: ReverbType.smallRoom, distortType: DistortType.drumsLoFi, filter: FilterType.bandPass),
    Effect(name: "Duck", pitch: 1.66, speed: 1.77, newEcho: [0.82, 0.82, 0.75], newReverb: ReverbType.plate, distortType: DistortType.drumsLoFi, filter: FilterType.bandPass),
    Effect(name: "Drunkard", pitch: 1.66, speed: 1.77, newEcho: [0.82, 0.82, 0.70], newReverb: ReverbType.plate, distortType: DistortType.drumsBufferBeats, filter: FilterType.bandPass),
    Effect(name: "Drinker", pitch: 1.66, speed: 0.9, newEcho: [0.82, 0.82, 0.70], newReverb: ReverbType.plate, distortType: DistortType.drumsBufferBeats, filter: FilterType.bandPass),
    Effect(name: "Cute", pitch: 1.66, speed: 0.9, newEcho: [0.29, 0.24, 0.37], newReverb: ReverbType.plate, filter: FilterType.bandPass),
    Effect(name: "Cute Robot", pitch: 1.66, speed: 1.24, newEcho: [0.7, 0.4, 0.7], newReverb: ReverbType.plate, distortType: DistortType.multiCellphoneConcert, filter: FilterType.bandPass),
    Effect(name: "Santa Claus", pitch: 1.29, speed: 0.5, newEcho: [0.2, 0.2, 0.2], newReverb: ReverbType.plate, distortType: DistortType.multiDistortedCubed, filter: FilterType.bandPass),
    Effect(name: "Old Man", pitch: 1.29, speed: 0.5, newEcho: [0.2, 0.2, 0.2], newReverb: ReverbType.plate, distortType: DistortType.multiDistortedFunk, filter: FilterType.bandPass),
    Effect(name: "Old Woman", pitch: 1.29, speed: 0.5, newEcho: [0.2, 0.2, 0.2], newReverb: ReverbType.plate, distortType: DistortType.multiDistortedSquared, filter: FilterType.bandPass),
    Effect(name: "Radio", pitch: 1.29, speed: 0.5, newEcho: [0.2, 0.2, 0.2], newReverb: ReverbType.plate, distortType: DistortType.speechGoldenPi, filter: FilterType.bandPass),
    Effect(name: "Radio 2", pitch: 1.54, speed: 0.63, newEcho: [0.25, 0.35, 0.2], newReverb: ReverbType.plate, distortType: DistortType.drumsLoFi, filter: FilterType.bandPass),
    Effect(name: "Caucasian", pitch: 1.55, speed: 0.66, newEcho: [0.25, 0.35, 0.3], newReverb: ReverbType.plate, distortType: DistortType.multiEverythingIsBroken, filter: FilterType.resonantLowShelf),
    Effect(name: "Santa Clause", pitch: 1.54, speed: 0.6, newEcho: [0.25, 0.3, 0.33], newReverb: ReverbType.plate, distortType: DistortType.multiEverythingIsBroken, filter: FilterType.lowShelf),
    Effect(name: "Ghost 2", pitch: 1.54, speed: 0.65, newEcho: [0.25, 0.3, 0.33], newReverb: ReverbType.plate, distortType: DistortType.multiDecimated4, filter: FilterType.resonantHighPass),
    Effect(name: "Well", pitch: 1.54, speed: 0.65, newEcho: [0.25, 0.3, 0.33], newReverb: ReverbType.plate, distortType: DistortType.speechCosmicInterference, filter: FilterType.resonantHighPass),
    Effect(name: "Shadow", pitch: 1.54, speed: 0.65, newEcho: [0.25, 0.3, 0.53], newReverb: ReverbType.plate, distortType: DistortType.multiDecimated2, filter: FilterType.resonantHighShelf),
  ];
}